[package]
name = "chipforge-cloud-api-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chipforge-common = { path = "../../../core/common" }
anyhow.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
